### ISSUE TITLE
Un po’ di roba

### ISSUE THREAD

**Issue by Bonfi97** [ArmeF97/OrarioTreni#10]
- Possibilità di salvare sia i singoli treni che le tratte nei preferiti.
- Quando si clicca su un treno si apre una schermata che mostra almeno tutte le informazioni che viaggiatreno mostra.
- Quando si clicca su una tratta vengono visualizzati tutti i treni che fanno quel determinato percorso e che sono già in viaggio su quella tratta e sotto quelli che partono in un orario uguale o successivo a quello in cui hai cliccato sulla tratta.
- Sempre dalla schermata della tratta deve essere possibile mostrare tutti i treni che viaggiano su quella tratta in un certo giorno e/o in un certo intervallo di ore.
- Avere l’opzione di visualizzare una tratta su una mappa (usando, ad esempio openstreetmaps) il percorso del treno con le relative fermate.
- La stessa cosa dovrebbe essere possibile dalla schermata che si visualizza quando si clicca su un singolo treno, ma, in aggiunta, se il treno è già partito, usare in dati di viaggaitreno per mostrare tra quali stazioni si trova.
- Già dalla schermata di ricerca si deve mostrare quali treni siano già partiti oppure quanto ritardo abbiamo.
- Deve essere possibile salvare le stazioni preferite e mostrare le informazioni relative sui treni in arrivo/partenza come su viaggiatreno.
- La possibilità di visualizzare il costo dei biglietti di una relativa tratta quando si clicca su essa, e poi avere la possibilità di cliccare su un prezzo per vedere tutti i treni che offrono un biglietto a quel prezzo (e a questo punto filtrarli per data/ora di partenza come scritto prima).
- Passare dal c# al c++.

**Comment by ArmeF97** [comment]
E' quasi tutto ben accetto, vedi sotto, ma ho preferito spezzare in issue diversi. Con questo, chiudo questo issue e ti rimando a quelli che ho linkato


Possibilità di salvare sia i singoli treni che le tratte nei preferiti.
https://github.com/ArmeF97/OrarioTreni/issues/12

Quando si clicca su un treno si apre una schermata che mostra almeno tutte le informazioni che viaggiatreno mostra.
https://github.com/ArmeF97/OrarioTreni/issues/13


Quando si clicca su una tratta vengono visualizzati tutti i treni che fanno quel determinato percorso e che sono già in viaggio su quella tratta e sotto quelli che partono in un orario uguale o successivo a quello in cui hai cliccato sulla tratta.
https://github.com/ArmeF97/OrarioTreni/issues/14
Dovrebbe essere già così, ma ti invito a esporre i dettagli sull'issue annesso

Sempre dalla schermata della tratta deve essere possibile mostrare tutti i treni che viaggiano su quella tratta in un certo giorno e/o in un certo intervallo di ore.
https://github.com/ArmeF97/OrarioTreni/issues/15

Avere l’opzione di visualizzare una tratta su una mappa (usando, ad esempio openstreetmaps) il percorso del treno con le relative fermate.
https://github.com/ArmeF97/OrarioTreni/issues/16

La stessa cosa dovrebbe essere possibile dalla schermata che si visualizza quando si clicca su un singolo treno, ma, in aggiunta, se il treno è già partito, usare in dati di viaggaitreno per mostrare tra quali stazioni si trova.
Questa è inclusa qui https://github.com/ArmeF97/OrarioTreni/issues/13 non credo ci sia bisogno di aprire un issue a parte


Già dalla schermata di ricerca si deve mostrare quali treni siano già partiti oppure quanto ritardo abbiamo.
https://github.com/ArmeF97/OrarioTreni/issues/17

Deve essere possibile salvare le stazioni preferite e mostrare le informazioni relative sui treni in arrivo/partenza come su viaggiatreno.
https://github.com/ArmeF97/OrarioTreni/issues/18

La possibilità di visualizzare il costo dei biglietti di una relativa tratta quando si clicca su essa, e poi avere la possibilità di cliccare su un prezzo per vedere tutti i treni che offrono un biglietto a quel prezzo (e a questo punto filtrarli per data/ora di partenza come scritto prima).
https://github.com/ArmeF97/OrarioTreni/issues/19

Passare dal c# al c++.
No.
